### ISSUE TITLE
v2 resource path doesn't handle `~/`

### ISSUE THREAD

**Issue by c-kruse** [skupperproject/skupper-ansible#40]
This one threw me for a loop:

This works:
```
- name: Setup skupper resources
  skupper.v2.resource:
    path: "/home/skupper/.sitedef"
    platform: podman
    remote: true
```
This fails with a FileNotFoundError:
```
- name: Setup skupper resources
  skupper.v2.resource:
    path: "~/.sitedef"
    platform: podman
    remote: true
```

Looks like a python thing: we'd need to use `os.path.expanduser` or some other file path handling to get this correct.
